### PR TITLE
Add flag to allow processing all packets

### PR DESCRIPTION
**Pull request by hit0ri**
This allows to passively scan Android 6.0+ devices (in my case it's Xiaomi Mi A1 with Android 8.1.0).

### CODE REVIEW

**Comment by schollz** [comment]
@hit0ri Thanks. I'll merge it soon, its a nice change. 

But on an aside - do you get usable tracking info from non-broadcasts? I tried doing non broadcasts before and the RSSI information was not location specific.

**Comment by hit0ri** [comment]
It works ok with one caveat. I need to use [this script](https://gist.github.com/hit0ri/aec2a34d31f6b9f58d8460fb12869450) to hop between channels on a scanner to capture non broadcast packets from other channels.

**Comment by schollz** [comment]
@hit0ri That's really cool! Would you mind if I put that into the scanner as well? There could be a flag `--all-frequencies` that enables a goroutine to automatically do what your script does.

**Comment by hit0ri** [comment]
Sure! That would be great!

**Pull request merged**
